### PR TITLE
ZEN-29566: fix ValueError in new device cProperty assignments.

### PR DESCRIPTION
**Pull request by jregovic**
Looping over values was not Python2 compatible, resulting in failed jobs when adding devices with cProperties

### CODE REVIEW

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by jregovic** [comment]
Any updates?

**Comment by jregovic** [comment]
Bump

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by csmouse** [comment]
Zenoss does not allow community contributions to this repo.

**Pull request closed without merging**
