### PR TITLE
ZEN-32417. Backported "Show all diffs on service migration test failures"

### PR DESCRIPTION
**Pull request by DeKapito**
Fixes ZEN-32417 (Improve ZenHub Config Retrieval Performance). The part of changes already was backported in the scope of ZEN-32572. This is backporting of remaining commit.

### CODE REVIEW

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by jpeacock-zenoss** [comment]
retest this

**Pull request merged**
