### PR TITLE
ZEN-22878 Escape names in search results

### PR DESCRIPTION
**Pull request by glujan**
[Jira](https://jira.zenoss.com/browse/ZEN-22878)

I had to reindex catalog to make it work.

### CODE REVIEW

**Comment by romanbakaleyko** [comment]
I would escape it in the UI side, reindexing can be very painfull for some customers.

**Comment by glujan** [comment]
Whole HTML snippet is send to the client side, so it is not possible to escape it in the UI.

We may, of course, try to escape some _dangerous_ tags on the UI but I don't think it's an elegant solution.

**Comment by rDr4g0n** [comment]
Reindexing may be necessary in the case that some unescaped values have already made it in, but this PR's purpose is to patch the hole rather than retroactively fix it.

**Comment by glujan** [comment]
@rDr4g0n Would you mind giving a review to this PR? I don't mind any type of review 😉

**Pull request merged**
