### PR TITLE
Remove Report All Monitored Components

### PR DESCRIPTION
**Pull request by d-terletskyi**
Fixes ZEN-33816.

To resolve the issue, the device report All Monitored Components was
removed since it no longer works for a large number of devices.

### CODE REVIEW

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Review by Deer-WarLord — APPROVED** [review]

**Comment by Deer-WarLord** [comment]
retest this

**Comment by d-terletskyi** [comment]
retest me, please

**Pull request merged**
