### PR TITLE
Feature: ZEN-34386

### PR DESCRIPTION
**Pull request by zendwhiting**

### CODE REVIEW

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Review by StevePC — APPROVED** [review]

**Comment by jpeacock-zenoss** [comment]
please test this

**Comment by jpeacock-zenoss** [comment]
please test this

**Pull request merged**
