### PR TITLE
Updated js regex mask to allow dots.

### PR DESCRIPTION
**Pull request by sbourg-zenoss**
Changes implemented in support of ZEN-33831 **Mappings in 4.x used to allow for periods in the instance name**

### CODE REVIEW

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Review by StevePC — APPROVED** [review]

**Comment by sbourg-zenoss** [comment]
test this

**Pull request merged**
