### PR TITLE
Update quiesce-mariadb.sh

### PR DESCRIPTION
**Pull request by ethirolle**
- get the database (zep or zodb) that corresponds to this mariadb container from the Envir Variable $MARIADB_DB (which must be set in Environment parameter of the service definitions for mariadb-model & mariab-events
- only run the pause (hold-lock) for that database
- see Jira ZEN-32461 for other dependencies/requirements, including needed changes to the service defs for the two mariadb services

### CODE REVIEW

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by dlysak** [comment]
retest this

**Comment by dlysak** [comment]
retest this

**Pull request merged**
