### PR TITLE
Fixes ZEN-32584

### PR DESCRIPTION
**Pull request by zsalinas**
Add audit logging to the devicemanagement router. Most complaints were around the lack of audit logging for Maintenance Window actions, however we were missing audit logging for User Command and Role assignments as well, this adds logging for all of those actions.

### CODE REVIEW

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by jpeacock-zenoss** [comment]
retest this

**Review by romanbakaleyko — CHANGES_REQUESTED** [review]
There is extended version of the fix in develop https://github.com/zenoss/zenoss-prodbin/pull/3800/files need to backport

**Pull request closed without merging**
