### PR TITLE
Add model API for Config Cache components

### PR DESCRIPTION
**Pull request by odubrovyk**
Implements ZEN-34675.

Added model API browser view for Config Cache components. 
It needs for RMMonitor ZP to be able to model these components.

### CODE REVIEW

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Review by jpeacock-zenoss — APPROVED** [review]

**Comment by jpeacock-zenoss** [comment]
retest this

**Pull request merged**
