### PR TITLE
Updated js regex mask.

### PR DESCRIPTION
**Pull request by sbourg-zenoss**
Updated regex mask for [ZEN-28389](https://jira.zenoss.com/browse/ZEN-28389)

### CODE REVIEW

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Review by StevePC — APPROVED** [review]

**Comment by sbourg-zenoss** [comment]
retest this

**Pull request merged**
