### PR TITLE
Add support for RBAC style role mappings

### PR DESCRIPTION
**Pull request by rphillipsz**
https://jira.zenoss.com/browse/ZEN-30611

RBAC role mappings come in the form "CZ0:CZAdmin", "CZ1:ZenOperator". If an Auth0 user logs in with any RBAC mapping, RM will only use the groups assigned to it's own CZ instance.  In other words, the above user when logging into cz0 will only have the CZAdmin role.  The same user logging
into cz1 will have the ZenOperator role.  If this user logs into cz2 he/she will have no roles.

In the absence of any RBAC style mappings, the list of roles from Auth0 will be returned as-is.  This means if you're using the zenoss-com connection and logging into a dev instance, you'll still have CZAdmin, even though you don't have any RBAC-assigned roles.

At some point in the future, group-role mappings in the Auth0 authorization extension will be removed, and the only roles from from Auth0 will be RBAC style assignments.

### CODE REVIEW

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by webhookbotuser** [comment]
Can one of the admins verify this patch?

**Comment by tgjonestx** [comment]
retest this

**Comment by rphillipsz** [comment]
retest this, please

**Pull request merged**
