### PR TITLE
ZEN-22458 Auto-close login failed events after successful login

### PR DESCRIPTION
**Pull request by carlcamera**
This closes out (in many but not all cases) the failed-login event for a server when
a successful SSH login occurs. See ZEN-22458 for details.

### CODE REVIEW

**Comment by carlcamera** [comment]
test again

**Comment by carlcamera** [comment]
retest this

**Comment by jplouis** [comment]
I read the comments in the ticket and do not understand why the "zCommandUsername" event cannot be cleared by zenmodeler.

**Comment by carlcamera** [comment]
Because we cannot spoof the context under which re run?  The zCommandUsername event is created under the context of zencommand. The modeler is running under zenmodeler. You were the one who helped me understand that we cannot "spoof" context.

**Pull request closed without merging**
