### PR TITLE
ZEN-17897: zenmib ignores 0 index in OID

### PR DESCRIPTION
**Pull request by fraibacas**

### CODE REVIEW

**Comment by jplouis** [comment]
What was the decision on how this reconciles with this ticket?  https://jira.zenoss.com/browse/ZEN-3770

**Comment by fraibacas** [comment]
From what I read in the ticket comments, oids containing zeros are valid oids so we need to revert what was done for ZEN-3770.

**Comment by jplouis** [comment]
Please verify with Brett or William.

**Comment by fraibacas** [comment]
William is ok with this approach:
"Seems good to me.  I also had Glenn and Ian take a look and they were fine with this approach."

**Comment by tgjonestx** [comment]
:+1:

**Pull request merged**
